### ISSUE TITLE
Password Security Concern - Encryption

### ISSUE THREAD

**Issue by VaishviShah** [SE-Fall24-G73/WolfJobsV2#10]
Currently, the password is stored directly in the database, instead we can encrypt the password and store and then decrypt the password at the time of login.

![image](https://github.com/user-attachments/assets/71e0ed49-7618-4f3e-8017-1f9d7d7a963a)

**Comment by Priyanshu9898** [comment]
> Currently, the password is stored directly in the database, instead we can encrypt the password and store and then decrypt the password at the time of login.
> 
> ![image](https://private-user-images.githubusercontent.com/83919024/382373974-71e0ed49-7618-4f3e-8017-1f9d7d7a963a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA0ODY2NzgsIm5iZiI6MTczMDQ4NjM3OCwicGF0aCI6Ii84MzkxOTAyNC8zODIzNzM5NzQtNzFlMGVkNDktNzYxOC00ZjNlLTgwMTctMWY5ZDdkN2E5NjNhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTAxVDE4MzkzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFjMzg4MGVmOTE4MjRiMjU2NTU1OTFmY2EwOTM1NGQyNjlmZTUzNjJjNWQwOTU2YTA0ZjNjMzZiMDE3YTE2ZGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.1ubeOjgu3c_7N8Zgcd11fMVN6661O_jQ9qD_YzK9roU)

Ohk I will add these functionality in the backend to enhance the security.

**Comment by VaishviShah** [comment]
Also, make sure when the user tries to sign up using the same email, the password stored in the database should not be changed.

**Comment by Priyanshu9898** [comment]
> Also, make sure when the user tries to sign up using the same email, the password stored in the database should not be changed.

Ohk, I will make sure of that.

**Comment by VaishviShah** [comment]
The feature is done!
