### ISSUE TITLE
MongoDB URL Update

### ISSUE THREAD

**Issue by VaishviShah** [SE-Fall24-G73/WolfJobsV2#11]
In the backend, we are currently using the local database url and it is visible in the backend code. Instead, let's create a .env file, setup MongoDB Atlas and use it in backend.

![image](https://github.com/user-attachments/assets/0a73236a-14a2-4d30-9c68-32401f9bd097)

**Comment by Priyanshu9898** [comment]
Ohk I will create .env file and add all secure variables inside of it.

**Comment by Priyanshu9898** [comment]
![image](https://github.com/user-attachments/assets/52f0a473-4150-47e6-af38-be5c4ea53dd7)

I have made my changes @VaishviShah.
