### ISSUE TITLE
Reset Password and Forgot Password Functionality in authentication

### ISSUE THREAD

**Issue by abhandary14** [SE-Fall24-G73/WolfJobsV2#12]
There is no provision to reset password if user forgets it. Create a forgot password functionality.

**Comment by Priyanshu9898** [comment]
> There is no provision to reset password if user forgets it. Create a forgot password functionality.

What should be the workflow???

**Comment by abhandary14** [comment]
> What should be the workflow???

User should be able to click on a forgot password link. Upon clicking they will get an email with a link to the reset password page.

**Comment by VaishviShah** [comment]
Created the Forgot Passoword Page:
![image](https://github.com/user-attachments/assets/21d16d23-c403-40e0-8cf5-014275e67851)

Built a provision to send reset link:
![image](https://github.com/user-attachments/assets/261a967b-d83a-4e47-b397-eddd7505898a)

**Comment by abhandary14** [comment]
Done!
