### ISSUE TITLE
Email Functionality

### ISSUE THREAD

**Issue by VaishviShah** [SE-Fall24-G73/WolfJobsV2#13]
1. Emails for Forgot Password function
2. Emails for applicants when there is any update in the application (When the manager accepts/rejects, the applicant should receive a mail)

**Comment by Priyanshu9898** [comment]
> 1. Emails for Forgot Password function
> 2. Emails for applicants when there is any update in the application (When the manager accepts/rejects, the applicant should receive a mail)

Ohk I will add the email functionality using node mailer for every situation where user should get the email and write the logic for that

**Comment by Priyanshu9898** [comment]
@VaishviShah @abhandary14 I have added emails for selection and rejection of candidate. But for forgot password, I need to work on different logic and have to make lot of changes, so I will create it in a next iteration with new issue.

**Comment by VaishviShah** [comment]
Okay
