### ISSUE TITLE
Candidate-Job Match Percentage

### ISSUE THREAD

**Issue by VaishviShah** [SE-Fall24-G73/WolfJobsV2#15]
Create a button that gives managers a functionality of getting match % for applicants using resume and job description.

**Comment by abhandary14** [comment]
> Create a button that gives managers a functionality of getting match % for applicants using resume and job description.

Okay, should I use a similar workflow as the ATS checker?

**Comment by VaishviShah** [comment]
> > Create a button that gives managers a functionality of getting match % for applicants using resume and job description.
> 
> Okay, should I use a similar workflow as the ATS checker?

Yes

**Comment by abhandary14** [comment]
> Yes

Will get started on it then.

**Comment by abhandary14** [comment]
![image](https://github.com/user-attachments/assets/371eb6ff-4ecc-4757-a39d-aba0efe68f93)

Added the functionality with a similar structure to the ATS score checker, but with a different prompt and job description fetching from database.

**Comment by VaishviShah** [comment]
Done!
