### ISSUE TITLE
Applicant Profile Enhancement

### ISSUE THREAD

**Issue by abhandary14** [SE-Fall24-G73/WolfJobsV2#16]
Add unity ID and student ID form fields to the applicant profile section.

**Comment by VaishviShah** [comment]
Okay

**Comment by abhandary14** [comment]
![image](https://github.com/user-attachments/assets/e5165757-6ecb-4699-995a-7ed4872d987b)

Added the two form fields.

**Comment by VaishviShah** [comment]
Okay
