### ISSUE TITLE
ATS score Checker for Applicant Resume

### ISSUE THREAD

**Issue by Priyanshu9898** [SE-Fall24-G73/WolfJobsV2#6]
User should check the ATS score of the resume when he uploads it.

**Comment by abhandary14** [comment]
What should be the workflow for this? Your expectations?

**Comment by Priyanshu9898** [comment]
> What should be the workflow for this? Your expectations?

=> Let's Make a GENAI model which gives ATS score for resume, Create a route in MERN backend, integrate model, create API.

**Comment by VaishviShah** [comment]
> > What should be the workflow for this? Your expectations?
> 
> => Let's Make a GENAI model which gives ATS score for resume, Create a route in MERN backend, integrate model, create API.

In the frontend part, there is a file called Resume.tsx in the Resume folder, call API using that file.

**Comment by abhandary14** [comment]
> In the frontend part, there is a file called Resume.tsx in the Resume folder, call API using that file.

Done, will get started

**Comment by abhandary14** [comment]
![image](https://github.com/user-attachments/assets/c10e36ad-5e1a-4105-9bb2-b21315febf96)

It is displaying the ATS score but it changes every time the button is clicked. Need to optimize the model's parameters and the prompt according.

**Comment by abhandary14** [comment]
I've implemented the functionality and resolved all bugs.

**Comment by VaishviShah** [comment]
> I've implemented the functionality and resolved all bugs.

Okay!
