### ISSUE TITLE
Make Responsive Landing Page and Navbar

### ISSUE THREAD

**Issue by Priyanshu9898** [SE-Fall24-G73/WolfJobsV2#7]
Make Responsive Landing Page and Navbar

1. Make them Responsive across all devices

**Comment by VaishviShah** [comment]
> Make Responsive Landing Page and Navbar
> 
> 1. Make them Responsive across all devices

What additional features should we add?

**Comment by Priyanshu9898** [comment]
> > Make Responsive Landing Page and Navbar
> > 
> > 1. Make them Responsive across all devices
> 
> What additional features should we add?

Features to  add:
1. Add Hamburger Menu on Mobile devices, So that User can easily access all files
2. When click on Hamburger, Drawer should be open, with all the links.
3. When User is Not logged In, the hamburger should not be visible on mobile devices.
4. When logged in, drawer should open when user click on hamburger with all the links
5. Drawer should close when user click on any link and should be able to go to that page.

**Comment by VaishviShah** [comment]
> > > Make Responsive Landing Page and Navbar
> > > 
> > > 1. Make them Responsive across all devices
> > 
> > 
> > What additional features should we add?
> 
> Features to add:
> 
> 1. Add Hamburger Menu on Mobile devices, So that User can easily access all files
> 2. When click on Hamburger, Drawer should be open, with all the links.
> 3. When User is Not logged In, the hamburger should not be visible on mobile devices.
> 4. When logged in, drawer should open when user click on hamburger with all the links
> 5. Drawer should close when user click on any link and should be able to go to that page.

Should I also add any animations to the drawer?

**Comment by abhandary14** [comment]
> Should I also add any animations to the drawer?

If possible add an animation where the drawer opens with a smooth transition.

**Comment by VaishviShah** [comment]
What should we change in the Landing Page?

**Comment by Priyanshu9898** [comment]
> What should we change in the Landing Page?

Landing page currently is not looking good on smaller devices, so we can make it responsive. You can add different image which is related to our project and enhance the styling.

![image](https://github.com/user-attachments/assets/9cf53e43-e8d6-49ea-a3ae-fc162dbbb993)

**Comment by VaishviShah** [comment]
Cool, I'll get on it!

**Comment by VaishviShah** [comment]
Updated the Landing Page 

![image](https://github.com/user-attachments/assets/a5582151-9a23-4a21-9ecf-5ee892da505f)

**Comment by VaishviShah** [comment]
Made responsive Landing Page. It does not show hamburger icon when the user is not logged in.

![image](https://github.com/user-attachments/assets/9063af91-cdf2-4f1c-9af0-b2add7db84f2)

The hamburger icon is visible on smaller devices and drawer when it is clicked. (only for loggedin users)

![Screenshot 2024-11-01 161341](https://github.com/user-attachments/assets/e911a74f-143c-41bd-99e2-b0a23cb363d1)

**Comment by VaishviShah** [comment]
I have implemented the functionalities and merged.

**Comment by abhandary14** [comment]
> I have implemented the functionalities and merged.

Done!

**Comment by abhandary14** [comment]
Closing issue.
