### ISSUE TITLE
Responsiveness of the Authentication Pages.

### ISSUE THREAD

**Issue by Priyanshu9898** [SE-Fall24-G73/WolfJobsV2#8]
Make Login and Signup Pages Responsive across all devices. Improve the styling of Toast messages, when successful or any error.

**Comment by VaishviShah** [comment]
> Make Login and Signup Pages Responsive across all devices. Improve the styling of Toast messages, when successful or any error.

Should i also add loader function so that the user does not click the login button again and again?

**Comment by Priyanshu9898** [comment]
> > Make Login and Signup Pages Responsive across all devices. Improve the styling of Toast messages, when successful or any error.
> 
> Should i also add loader function so that the user does not click the login button again and again?

Yes that would be better, and try to add spinner and make button disable when logging in....

**Comment by VaishviShah** [comment]
I am also thinking of adding animations to the button with spring and scale effects.

**Comment by Priyanshu9898** [comment]
> I am also thinking of adding animations to the button with spring and scale effects.

yes, that would be better. Also for the toast message, you can use react-hot-toast library.

**Comment by VaishviShah** [comment]
Ok

**Comment by Priyanshu9898** [comment]
Can you please add login with google button in both the pages, so that I can implement, login with google functionality from backend?

**Comment by VaishviShah** [comment]
> Can you please add login with google button in both the pages, so that I can implement, login with google functionality from backend?

Sure, will do that as well.

**Comment by VaishviShah** [comment]
Completed all required functionalities

Updated Login Page (responsive, styling of toast messages and its functions, animated button):

![image](https://github.com/user-attachments/assets/ab8c92d3-9f66-4ce1-b5ab-bc8ea6e8cb79)

![image](https://github.com/user-attachments/assets/c05936a0-4d42-43e1-892a-9b806036155c)


Updated Register/SignUp page:

![image](https://github.com/user-attachments/assets/a294e34f-6fe0-456a-b5a1-c41b75e91559)

![image](https://github.com/user-attachments/assets/c2151e73-b38c-445b-9b4a-af5f249d7e86)

**Comment by abhandary14** [comment]
Done!
