### ISSUE TITLE
Better Design and functionality for Notification Icon

### ISSUE THREAD

**Issue by Priyanshu9898** [SE-Fall24-G73/WolfJobsV2#9]
In mobile devices, the notification icons and other pages link does not visible, so when you create a drawer we can not add that page there, so can you please enhance the styling of that?

![image](https://github.com/user-attachments/assets/b95f04d9-5046-4fb1-971d-1592d5593f77)

**Comment by VaishviShah** [comment]
Okay, will do that as well!

**Comment by VaishviShah** [comment]
Added the notification icon to declutter the whole view.

![image](https://github.com/user-attachments/assets/8373b4af-a2c8-41d5-9221-3bc875988561)

**Comment by VaishviShah** [comment]
Also, the dropdown menu - drawer with animations and made the navigation bar responsive.

![image](https://github.com/user-attachments/assets/b9602f95-6b5f-4b74-b06d-56d093bfb341)
